### ISSUE TITLE
Have u considered using morton codes for storing coords?

### ISSUE THREAD

**Issue by trsh** [vanruesc/linear-octree#2]
Or does this fallow the principles in https://geidav.wordpress.com/2014/08/18/advanced-octrees-2-node-representations/ ?

**Comment by vanruesc** [comment]
Hi,

I haven't looked much into morton codes. Are there any advantages to using that specific representation that I should know of?

The coordinate key design in this library is based on https://voxelfarm.helpdocsonline.com/world-octree
Furthermore, it's specifically designed around the 53-bit integer limitation in JavaScript and uses 21 bits for X and Z each and 11 bits for Y by default:

![bits](https://user-images.githubusercontent.com/9214917/72931583-68a3b200-3d5e-11ea-8c17-84ab26ddd128.jpg)

I know about [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) but have yet to check the performance impact of using that feature for this specific use case.

**Comment by trsh** [comment]
Do you also store LOD?

**Comment by trsh** [comment]
I see the demo is unfinished. How do you test this lib? Is it working at all? How to I  push something into the octree? I mean the whole point of an octree is to add and remove points/nodes/etc.

**Comment by vanruesc** [comment]
> Do you also store LOD?

LOD is currently not part of the key design because of the limited amount of available bits. For that reason, LOD indices are stored separately. The octree uses multiple hash maps that represent separate LOD grids which [can be selected](https://github.com/vanruesc/linear-octree/blob/master/src/core/Octree.js#L317) via the LOD index.

> I see the demo is unfinished. How do you test this lib? Is it working at all?

This project is a work in progress as indicated in the readme. It will support the kind of operations you're looking for when it's complete.

**Comment by trsh** [comment]
@vanruesc ok, cool, thank you. So good luck and keep the good work going. I hope you finish soon, as I will need this for one of my projects :))
