### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by enbugger** [vanruesc/linear-octree#3]
Hi.

I've been trying to launch the demo page locally but with no luck. Github pages deployment is no more as well. Perhaps, it would be quicker to ask you directly here. 
Is this implementation considered to be finished by you as an author? Besides raytracing logic.

**Comment by vanruesc** [comment]
Hi,

this project is still incomplete and the demo mostly consists of placeholder code. I never got around to finishing it because other projects take up most of my free time. However, I still want to finish it at some point.

I'll keep in mind that there's interest in this project, but I can't say when I'll be able to put time into it.

**Comment by vanruesc** [comment]
This library is now functional since `v0.1.0`. The base functionality is complete but there might still be bugs, so feel free to report any issues you might find.

Next on the list is a higher-level octree implementation for 3D objects with bounding spheres. However, this will have to wait until I have more time on my hands.
